name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  schedule:
    - cron:  '0 4 * * 5' # Fridays at 4am

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint:js

      - name: Test
        run: yarn test
